# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('fullname', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('score', models.FloatField(blank=True, default=5.0, null=True)),
            ],
        ),
    ]
